jaredhendrickson13/pfsense-api

- pfSense-pkg-API/files/etc/inc/api/framework/APIResponse.inc
- pfSense-pkg-API/files/etc/inc/api/framework/APITools.inc
- pfSense-pkg-API/files/etc/inc/api/models/APIFirewallRuleCreate.inc
- pfSense-pkg-API/files/etc/inc/api/models/APIFirewallRuleUpdate.inc
- tests/test_api_v1_firewall_rule.py
- Allows clients to create/update firewall rules with a gateway group in the `gateway` field.
- Adds validation to only allow clients to set a firewall rule's `gateway` field if the IP protocol of the rule object matches the gateway's IP protocol value.
- Fixes bug that prevented clients from updating the `log` field on firewall rules.
- Fixes bug that allowed clients to create/update gateway objects that use an existing gateway group name.
- Breaks down firewall rule validation to smaller and easier to understand methods.
- Fixes bad PUT payload value in `test_api_v1_firewall_rule.py` unit test.
> Firewall rule enhancements

- pfSense-pkg-API/files/etc/inc/api/framework/APITools.inc
- pfSense-pkg-API/files/etc/inc/api/models/APIFirewallStatesRead.inc
- pfSense-pkg-API/files/etc/inc/api/models/APIFirewallStatesSizeRead.inc
- Fixes parsing bug in APIFirewallStatesRead.inc that prevented the firewall states table from being parsed correctly on some interfaces
- Adds the `age`, `expires_in`, `packets_total`, `packets_in`, `packets_out`, `bytes_total`, `bytes_in`, and `bytes_out` field to returned firewall states
> Firewall States Parsing Fix

- pfSense-pkg-API/files/etc/inc/api/framework/APIModel.inc
- pfSense-pkg-API/files/etc/inc/api/framework/APITools.inc
- Allows virtual IPs to respond to API requests when the virtual IPs interface matches the `allowed_interfaces` API setting (IPv4 CARP or IP Alias virtual IPs only)
- Adds `is_ip_vip()` function to check if a provided IP is a configured virtual IP on the system
- Adds `is_ip_in_cidr()` function to check if provided IP is within a provide CIDR
> API requests via virtual IP

- pfSense-pkg-API/files/etc/inc/api/models/APIInterfaceCreate.inc
- pfSense-pkg-API/files/etc/inc/api/models/APIInterfaceUpdate.inc
When creating or updating an interface with track6 as the type6 setting, 
the API currently always writes 0 as the prefix id, regardless of the actually specified id.
This is cause by an incorrect identifier in the validated_data array.
Here `track6-prefix-id--hex` is set, but the identifier should actually be `track6-prefix-id`.
This PR fixes that, and has been tested on pfsense 2.5.
>  Fix track6-prefix-id on interface create/update

- pfSense-pkg-API/files/etc/inc/api/models/APISystemCertificateUpdate.inc
This PR makes sure that updated certificates are also stored base64-encoded.
Fixes https://github.com/jaredhendrickson13/pfsense-api/issues/218
> Fix updated certificates to be b64 encoded as well

- pfSense-pkg-API/files/etc/inc/api/endpoints/APIServicesUnboundHostOverrideFlush.inc
- pfSense-pkg-API/files/etc/inc/api/models/APIServicesUnboundHostOverrideFlushDelete.inc
- pfSense-pkg-API/files/usr/local/www/api/documentation/openapi.yml
- tests/test_api_v1_services_unbound_host_override_flush.py
- Adds /api/v1/services/unbound/host_override/flush endpoint to allow deletion of all existing host overrides
> Allow flushing of all Unbound host overrides

- pfSense-pkg-API/files/etc/inc/api/framework/APIResponse.inc
- pfSense-pkg-API/files/etc/inc/api/models/APISystemPackageCreate.inc
- pfSense-pkg-API/files/etc/inc/api/models/APISystemPackageDelete.inc
- pfSense-pkg-API/files/usr/local/www/api/documentation/openapi.yml
- tests/test_api_v1_system_package.py
- Fixes bug that prevented menu items from being installed after installing a new package via /api/v1/system/package (#223)
- Removes ability to install packages via URL, and removes `timeout` and `force` fields as the endpoint now calls pre-existing pfSense functions.
> Fix package installations via /api/v1/system/package

- docs/CONTRIBUTING.md
- pfSense-pkg-API/files/etc/inc/api/endpoints/APIFirewallRuleFlush.inc
- pfSense-pkg-API/files/etc/inc/api/endpoints/APIRoutingGatewayDefault.inc
- pfSense-pkg-API/files/etc/inc/api/endpoints/APIServicesUnboundHostOverrideFlush.inc
- pfSense-pkg-API/files/etc/inc/api/framework/APIResponse.inc
- pfSense-pkg-API/files/etc/inc/api/models/APIFirewallRuleCreate.inc
- pfSense-pkg-API/files/etc/inc/api/models/APIFirewallRuleFlushUpdate.inc
- pfSense-pkg-API/files/etc/inc/api/models/APIRoutingGatewayDefaultUpdate.inc
- pfSense-pkg-API/files/etc/inc/api/models/APIServicesUnboundHostOverrideFlushUpdate.inc
- pfSense-pkg-API/files/usr/local/www/api/documentation/openapi.yml
- tests/test_api_v1_firewall_rule_flush.py
- tests/test_api_v1_routing_gateway_default.py
- tests/test_api_v1_services_unbound_host_override_flush.py
- tools/README.md
- Adds support for PUT requests to /api/v1/services/unbound/host_override/flush endpoint to replace all host overrides with a list of specified host overrides.
- Adds /api/v1/routing/gateway/default endpoint to update the default gateway. (#231)
- Documentation enhancements.
> v1.4.2 Fixes & Features

- pfSense-pkg-API/files/etc/inc/api/endpoints/APIServicesWOLSend.inc
- pfSense-pkg-API/files/etc/inc/api/framework/APIResponse.inc
- pfSense-pkg-API/files/etc/inc/api/models/APIServicesWOLSendCreate.inc
- pfSense-pkg-API/files/usr/local/www/api/documentation/openapi.yml
- tests/test_api_v1_services_wol_send.py
Hello  @jaredhendrickson13 ,
we need WOL via pfsense API. This PR enables us to have this feature. It would be great if it was merged.
WDYT?
Best regards and thanks
> Add /api/v1/services/wol/send/ endpoint to be able to send a WOL packet

- README.md
- Adjusts README.md to state only pfSense on AMD64 systems is supported.
> AMD64 install requirement

- pfSense-pkg-API/files/etc/inc/api/endpoints/APIInterfaceGroup.inc
- pfSense-pkg-API/files/etc/inc/api/framework/APIResponse.inc
- pfSense-pkg-API/files/etc/inc/api/framework/APITools.inc
- pfSense-pkg-API/files/etc/inc/api/models/APIFirewallRuleCreate.inc
- pfSense-pkg-API/files/etc/inc/api/models/APIFirewallRuleUpdate.inc
- pfSense-pkg-API/files/etc/inc/api/models/APIInterfaceGroupCreate.inc
- pfSense-pkg-API/files/etc/inc/api/models/APIInterfaceGroupDelete.inc
- pfSense-pkg-API/files/etc/inc/api/models/APIInterfaceGroupRead.inc
- pfSense-pkg-API/files/etc/inc/api/models/APIInterfaceGroupUpdate.inc
- pfSense-pkg-API/files/usr/local/www/api/documentation/openapi.yml
> Fix validate interface for firewall rule creation to support interface groups

- pfSense-pkg-API/files/usr/local/www/api/documentation/openapi.yml
- Fixes typo in /api/v1/system/api documentation that wrongfully states the 'allowed_interfaces' field as 'available_interfaces' (#246)
> Fix typo for 'allowed_interfaces' on /api/v1/system/api documentation

- tests/run_all_tests.py
- tests/test_api_v1_user_group_member.py
- Changes run_all_tests.py to execute each test in alphabetical order.
- Fixes issue test_api_v1_user_group_member.py that would revoke the `admin` user's admin privileges causing all subsequent tests to fail with a 403 forbidden response.
> Control test's order of precedence

- pfSense-pkg-API/files/etc/inc/api/endpoints/APIFirewallAliasAdvanced.inc
- pfSense-pkg-API/files/etc/inc/api/framework/APIResponse.inc
- pfSense-pkg-API/files/etc/inc/api/models/APIFirewallAliasAdvancedRead.inc
- pfSense-pkg-API/files/etc/inc/api/models/APIFirewallAliasAdvancedUpdate.inc
- pfSense-pkg-API/files/usr/local/www/api/documentation/openapi.yml
- tests/test_api_v1_firewall_alias_advanced.py
- Adds APIFirewallAliasAdvancedRead and APIFirewallAliasAdvancedUpdate models to read and update advanced alias settings normally found in /system_advanced_firewall.php. 
- Adds APIFirewallAliasAdvanced endpoint at /api/v1/firewall/alias/advanced to call above models on GET and PUT respectively.
- Adds E2E tests for /api/v1/firewall/alias/advanced
- Adds API documentation on /api/v1/firewall/alias/advanced with available properties, methods, etc.
> Advanced alias endpoint

- pfSense-pkg-API/files/etc/inc/api/endpoints/APIServicesServiceWatchdog.inc
- pfSense-pkg-API/files/etc/inc/api/framework/APIResponse.inc
- pfSense-pkg-API/files/etc/inc/api/models/APIServicesServiceWatchdogRead.inc
- pfSense-pkg-API/files/etc/inc/api/models/APIServicesServiceWatchdogUpdate.inc
- pfSense-pkg-API/files/usr/local/www/api/documentation/openapi.yml
- tests/test_api_v1_services_service_watchdog.py
- Adds the /api/v1/services/service_watchdog endpoint to read and update Service Watchdog configurations.
> Service Watchdog endpoint

- pfSense-pkg-API/files/etc/inc/api/endpoints/APISystemVersionUpgrade.inc
- pfSense-pkg-API/files/etc/inc/api/framework/APIResponse.inc
- pfSense-pkg-API/files/etc/inc/api/models/APISystemVersionUpgradeRead.inc
- pfSense-pkg-API/files/usr/local/www/api/documentation/openapi.yml
- tests/test_api_v1_system_version_upgrade.py
- adds the /api/v1/system/version/upgrade endpoint to read available pfSense upgrades
- adds the `page-system-update-settings` to /api/v1/system/version endpoint
- adjusts minor documentation and response verbiage
> feat: read available pfsense upgrades

- pfSense-pkg-API/files/etc/inc/api/framework/APIAuth.inc
- pfSense-pkg-API/files/etc/inc/api/models/APISystemAPISyncUpdate.inc
- pfSense-pkg-API/files/etc/inc/api/models/APISystemAPIUpdate.inc
- pfSense-pkg-API/files/usr/local/www/api/documentation/openapi.yml
- pfSense-pkg-API/files/usr/local/www/api/index.php
- requirements.txt
- tests/test_api_v1_system_api.py
- Changes API Login Protection to only log failed authentication attempts by default (#287)
- Adds the `log_successful_auth` field to /api/v1/system/api and System > API page to optionally enable logging of successful authentication attempts (#287)
- Fixes bug that prevented persistent backups from being taken on /api/v1/system/api and /api/v1/system/api/sync (#288)
- Fixes validation for `hasync_*` fields in /api/v1/system/api (#290)
> v1.5.1 Fixes

- pfSense-pkg-API/files/etc/inc/api/models/APIFirewallRuleRead.inc
Hi,
Goal of this PR is to improve useability of endpoint `GET /api/firewall/rule`. Some fields can be converted to boolean instead of return empty strings. Impacted fields :
- `log`
- `floating`
- `disabled`
`GET /api/firewall/rule` before this PR:
```json
{
"status": "ok",
"code": 200,
"return": 0,
"message": "Success",
"data": [
{
"id": "",
"tracker": "1668766583",
"type": "block",
...
"disabled": "",
"log": ""
}
]
}
```
`GET /api/firewall/rule` after this PR:
```json
{
"status": "ok",
"code": 200,
"return": 0,
"message": "Success",
"data": [
{
"id": "",
"tracker": "1668766583",
"type": "block",
...
"disabled": true,
"floating": false,
"log": true
}
]
}
```
> feat: Get filter rules: Convert some fields to booleans

- pfSense-pkg-API/files/etc/inc/api/models/APIFirewallRuleCreate.inc
Hi,
Here is a PR to add the possiblity to create a new floating rule, without specifying interface 
Example payload (`POST api/v1/firewall/rule`):
```json
{
"descr": "Floating Rule no interface",
"type": "pass",
"src": "any",
"srcport": "any",
"dst": "any",
"dstport": "any",
"protocol": "tcp",
"floating": true,
"interface": null,
"disabled": false,
"ipprotocol": "inet46",
"log": false,
"top": false
}
```
> feature: Create a floating rule without interface

- pfSense-pkg-API/files/etc/inc/api/models/APIFirewallNATOutboundMappingCreate.inc
- pfSense-pkg-API/files/etc/inc/api/models/APIFirewallNATOutboundMappingUpdate.inc
Port ranges must always be separated by :, this commit fixes the context in a few replace statements that replace the : with -
> fix: fix context in port range replaces (#327)

- pfSense-pkg-API/files/etc/inc/api/framework/APIQuery.inc
- pfSense-pkg-API/files/etc/inc/api/framework/APITools.inc
- pfSense-pkg-API/files/etc/inc/api/models/APIFirewallNATOutboundMappingCreate.inc
- pfSense-pkg-API/files/etc/inc/api/models/APIFirewallNATOutboundMappingUpdate.inc
- pfSense-pkg-API/files/etc/inc/api/models/APIStatusSystemRead.inc
- pfSense-pkg-API/files/etc/inc/api/models/APISystemCARead.inc
- pfSense-pkg-API/files/etc/inc/api/models/APISystemCertificateRead.inc
- pfSense-pkg-API/files/usr/local/www/api/documentation/openapi.yml
- Fixes issue where GET /api/v1/system/ca would return an associative array of CAs instead of a sequential array (#357)
- Fixes issue where GET /api/v1/system/certificate would return an associative array of certs instead of a sequential array (#357)
- Loosens type checking when sorting NAT rules (#352)
- Adds documentation for `server_addr` field on /api/v1/services/openvpn/client (#360)
- Bumps `php-jwt` dependency to v6.7.0
> v1.5.4 Fixes

- .github/workflows/build.yml
- .github/workflows/release.yml
- pfSense-pkg-API/files/etc/inc/api/models/APIFirewallAliasEntryCreate.inc
- pfSense-pkg-API/files/etc/inc/api/models/APISystemAPIVersionRead.inc
- tests/test_api_v1_firewall_alias.py
- tools/make_package.py
- Fixes issue with POST /api/v1/firewall/alias/entry that allowed an extra alias `detail` item to be appended. #374 
- Uses `pkg-static` for API version lookups instead of `pkg`. #373
> v1.6.1 Fixes

- pfSense-pkg-API/files/etc/inc/api/framework/APIResponse.inc
- pfSense-pkg-API/files/etc/inc/api/framework/APITools.inc
- pfSense-pkg-API/files/etc/inc/api/models/APIAccessTokenCreate.inc
- pfSense-pkg-API/files/etc/inc/api/models/APIFirewallNATOutboundMappingCreate.inc
- pfSense-pkg-API/files/etc/inc/api/models/APIServicesIPsecPhase1Create.inc
- pfSense-pkg-API/files/etc/inc/api/models/APIServicesIPsecPhase1Update.inc
- tests/e2e_test_framework/__init__.py
- tests/test_api_v1_access_token.py
- tests/test_api_v1_services_ipsec_phase1.py
- Fixes issue where API sync with no headers threw fatal errors (fixes #380)
- Relaxes input validation for `remote-gateway` field on /api/v1/services/ipsec/phase1 (fixes #382)
- Fixes an issue where client were unable to obtain access tokens via API without `page-all` privileges (fixes #384)
- Fixes an issue where an error was thrown when attempting to create new outbound NAT mappings when no mappings exist initially (fixes #385)
> v1.6.2 Fixes

- tools/templates/Makefile.j2
This is to resolve this issue: https://github.com/jaredhendrickson13/pfsense-api/issues/239
Netgate devices run on arm, and by default FreeBSD will make the package specific to whatever architecture you build it on. By adding `NO_ARCH=yes` the package will not be architecture specific and so it won't require that you force install. It also allows you to do automatic updates.
You might have thought that Netgate would get around to making their own api for pfsense+ like you mentioned in [this issue](https://github.com/jaredhendrickson13/pfsense-api/issues/140), sadly not.
> Package is no longer architecture specific

- README.md
- pfSense-pkg-API/files/etc/inc/api/models/APISystemAPIVersionRead.inc
- Relaxes architecture requirement for package install.
- Fixes issue where API version comparisons fail on PHP 8+.
> v1.6.3 Fixes

- pfSense-pkg-API/files/usr/local/share/pfSense-pkg-API/manage.php
- pfSense-pkg-API/files/usr/local/www/api/update/index.php
- Addresses an issue where the `revert` cli command did not properly escape input
- Fixes an issue where the identified version was not escaped during API updates.
> v1.6.4 Fixes

- .github/workflows/build.yml
- .github/workflows/release.yml
- README.md
- composer.json
- composer.lock
- docs/SECURITY.md
- pfSense-pkg-API/files/etc/inc/api/models/APIFirewallNATOutboundMappingCreate.inc
- pfSense-pkg-API/files/etc/inc/api/models/APIFirewallNATOutboundMappingUpdate.inc
- pfSense-pkg-API/files/etc/inc/api/models/APIInterfaceApplyCreate.inc
- tests/test_api_v1_interface.py
- tests/test_api_v1_services_service_watchdog.py
- tests/test_api_v1_system_package.py
- Uses new internal field names `target` and `target_subnet` for outbound NAT #422 
- Updates APIInterfaceApplyCreate to use new pfSense 2.7.1+ functions
- Bumps `php-jwt` to 6.10.0
_Note: pfSense 2.7.1+ contains some breaking changes that forces this release to deprecate support for pfSense 2.7.0._
> v1.7.0 Fixes

- pfSense-pkg-API/files/etc/inc/api/models/APISystemAPIVersionRead.inc
- Adds a condition to return an empty array  in if the identified $releases is not an array in `APISystemAPIVersionRead::get_github_releases()`
> fix: ensure APISystemAPIVersionRead::get_github_releases() always returns array

- pfSense-pkg-API/files/etc/inc/api/framework/APITools.inc
In the current version, changing the order of nat rules has no effect. This patch fixes this bug.
> fix: save sorted nat rules

- pfSense-pkg-API/files/etc/inc/api/models/APISystemCertificateCreate.inc
> now when importing a certificate, it doesn't have the field 'type'

- pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Models/OpenVPNServer.inc
- pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Tests/APIModelsOpenVPNServerTestCase.inc
- Fixed an issue where an OpenVPNServer could not be assigned an `authmode` of `Local Database`. #561
> v2.1.2 Fixes

- docs/COMMON_CONTROL_PARAMETERS.md
- pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Core/Model.inc
- pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Dispatchers/RESTAPISettingsSyncDispatcher.inc
- pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Forms/SystemRESTAPISettingsForm.inc
- pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Models/DHCPServerStaticMapping.inc
- pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Models/IPsecPhase1.inc
- pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Models/RESTAPISettings.inc
- pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Tests/APIModelsAPISettingsTestCase.inc
- pfSense-pkg-RESTAPI/files/usr/local/share/pfSense-pkg-RESTAPI/info.xml
- tools/make_package.py
- Adds the `override_sensitive_fields` REST API setting to allow admins to override field's `sensitive` property. #582 
- Add `auto` as a choice for the IPsecPhase1 `myid_type` and `peerid_type` fields. #584
- Increases the maximum number of queued API sync processes to 1024.
- Sort DHCPServerStaticMappings by `ipaddr` #583
- Fixes an issue that prevented the package from being built on FreeBSD versions that no longer have upstream port tree support.
> v2.2.1 Fixes & Features

- .github/workflows/release.yml
- pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Models/WireGuardPeerAllowedIP.inc
- tools/make_package.py
- Reduces the minimum requirement for WireGuardPeerAllowedIP `mask` field from 1 to 0. #595 
- Prevents a warning that would occur when `pfSense-repoc` is called with the package installed. #588 
- Tests have been removed from full release builds of the package. #588
> v2.2.2 Fixes

- pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Models/OpenVPNClient.inc
- pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Tests/APIModelsOpenVPNClientTestCase.inc
In the latest version of openvpn-2.6.8_1
there is a mandatory server_port field. But this field is missing in the API. This makes it impossible to work with OpenVPN VPN clients.
> added openvpn server port

- pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Models/FirewallRule.inc
As far as I understood, in the firewall rules in the api, you can select only a gateway with a static ip address, but for firewall rules you can also connect a gateway with a dynamic address (for example, OpenVPN).
The tag field has also been added.
> Fixed adding a gateway with a dynamic address to Firewall Rules. Added tag field to Firewall Rules

- composer.lock
- pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Core/Endpoint.inc
- pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Core/Form.inc
- pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Forms/SystemRESTAPIUpdatesForm.inc
- Provides better error messages that inherently occur during package updates
- Gives more descriptive notice of behavior when the package is updating
> fix: improve error handling during package updates #633

- pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Core/Model.inc
- pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Models/FirewallAlias.inc
- pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Models/PortForward.inc
- pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Tests/APIModelsFirewallRuleTestCase.inc
- pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Tests/APIModelsPortForwardTestCase.inc
- Fixes an issue where PortForward associated rules were created/updated incorrectly #659 
- Fixes an issue where the client's username and IP were not correctly passed to new objects when all firewall rules were replaces
- Fixes an issue where firewall aliases of different types could not be nested
> v2.3.4 Fixes

- pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Caches/PrivilegesCache.inc
- pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Core/Form.inc
- Fixes issues with matching UI permissions to REST API form pages (#658)
- Minor privilege name improvements
> v2.3.5 Fixes

- pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Models/IPsecChildSAStatus.inc
- pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Tests/APICoreModelTestCase.inc
- Fixes a bad function reference that resulted in a 500 error on /api/v2/status/ipsec/child_sa
> fix: correct internal callable name in IPsecChildSAStatus

- .github/workflows/schedule_weekly.yml
- README.md
- composer.lock
- docs/INSTALL_AND_CONFIG.md
- docs/SECURITY.md
- docs/index.md
- mkdocs.yml
- package-lock.json
- package.json
- pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Core/Endpoint.inc
- pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Core/Form.inc
- pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Core/Model.inc
- pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Endpoints/ServicesDHCPRelayEndpoint.inc
- pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Models/BINDZone.inc
- pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Models/DHCPRelay.inc
- pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Models/DHCPServer.inc
- pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Models/HAProxyBackend.inc
- pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Models/OpenVPNClient.inc
- pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Models/Service.inc
- pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Schemas/OpenAPISchema.inc
- pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Tests/APIModelsBINDZoneTestCase.inc
- pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Tests/APIModelsDHCPRelayTestCase.inc
- pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Tests/APIModelsDHCPServerTestCase.inc
- pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Tests/APIModelsHAProxyBackendTestCase.inc
- pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Tests/APIModelsOpenVPNClientTestCase.inc
- pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Tests/APIModelsServiceTestCase.inc
- pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Tests/APIModelsWireGuardSettingsTestCase.inc
- Adds /api/v2/services/dhcp_relay endpoint for configuring the DHCP Relay service (#121)
- Adds support for SSL offloading in /api/v2/services/haproxy/frontend endpoints (#661)
- Adds endpoints for /api/v2/services/haproxy/frontend/certificate (#661)
- Fixes an issue where some services' status was not accurately obtained (#634)
- Fixes an issue where the WireGuard service's enabled status was not always represented correctly
- Fixes an issue where the /api/v2/services/dhcp_server endpoints could not be used if any DHCP Relay configuration is currently in the config
- Fixes an issue where /api/v2/services/dhcp_server did not accurately determine if a DHCP Relay was running
- Makes /api/v2/services/haproxy/backend's `advanced_backend` field a Base64Field instead of plain StringField …
> v2.4.0 Fixes & Features

- pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Tests/APICoreModelTestCase.inc
- Fixes an issue that prevented HAProxyFrontends from being applied via API (#677)
> v2.4.1 Fixes

- composer.lock
- pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Models/DNSResolverSettings.inc
- pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Tests/APICoreModelTestCase.inc
- pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Tests/APIModelsDNSResolverSettingsTestCase.inc
- Fixes an issue that prevented DNSResolverSettings `python_script` choices from being obtained. Fixes #681.
> v2.4.2 Fixes

- pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Core/ContentHandler.inc
- pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Models/NetworkInterface.inc
- pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Models/RoutingGatewayGroupPriority.inc
- pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Tests/APICoreContentHandlerTestCase.inc
- pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Tests/APIModelsRoutingGatewayGroupPriorityTestCase.inc
- Fixes an issue that prevented RoutingGatewayGroupPriority objects from being updated. #707
- Fixes an issue that prevented the NetworkInterface `gateway` and `gatewayv6` fields from being assigned when interfaces were not represented by ID.
- The `id` and `parent_id` fields are now included in OpenAPI response examples. #713
> v2.5.1 Fixes

- pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Fields/FloatField.inc
- pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Models/SystemStatus.inc
- pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Tests/APIModelsSystemStatusTestCase.inc
- Fixes an issue where the assigned system language could prevent SystemStatus's `cpu_load_average` field from being correctly parsed into an array #716 
- Fixes unexpected newlines in FloatField error messages
> v2.5.2 Fixes

- pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Models/PortForward.inc
- pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Tests/APIModelsPortForwardTestCase.inc
- Adds `any` to available `protocol` choices in PortForward (#721)
- Allows `target` to be set to an interface IP accessor in PortForward (#721)
> v2.5.3 Features

- pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Models/FirewallAlias.inc
- pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Validators/LengthValidator.inc
- Adds easier method of excluding model fields from maximum length constraints
- Addresses an issue where FirewallAlias `address` and `detail` items were limited to a maximum of 128 items (#745)
> v2.5.4 Fixes

- pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/Fields/SpecialNetworkField.inc
- Addresses an issue that could cause timeouts when reading PortForwards due to excessive reloading of objects. Fixes #749.
> v2.6.1 Fixes
